# testing
kerker.tw:
  user: ubuntu
  port: 22
  stage: testing
  path: ~/www/mazu
  remote: origin
  branch: master

# production
gps.kerker.tw:
  user: ubuntu
  port: 22
  stage: production
  path: ~/www/mazu
  remote: origin
  branch: master
